import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryProvider } from "@/components/providers/QueryProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap', // Avoids invisible text while loading
});

export const metadata: Metadata = {
  title: "Robia Copilot",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_robia_copilot.svg",
    shortcut: "/logo_robia_copilot.svg",
    apple: "/logo_robia_copilot.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className}`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <TooltipProvider>
            {children}
          </TooltipProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
