// RC-25 frontend scheduling UI — everything here is pure, client-side text
// generation/parsing/formatting. It never talks to the backend and never
// computes when a schedule will actually next fire: that stays the
// backend's own single source of truth (AutomationsService.resolveNextRunAt
// / cron-schedule.ts), read back verbatim as `Automation.nextRunAt`. This
// module's only job is to spare a non-technical user from having to type a
// raw cron expression by hand, while never generating anything the
// backend's own strict 5-field validator would reject.

export type ScheduleFrequency = 'daily' | 'weekly' | 'monthly'

// Sunday=0 .. Saturday=6 — the same convention cron itself uses, so a
// weekday value round-trips through buildCronExpression()/parseCronPreset()
// without translation.
export const WEEKDAY_OPTIONS: Array<{ value: number; label: string }> = [
  { value: 0, label: 'Dimanche' },
  { value: 1, label: 'Lundi' },
  { value: 2, label: 'Mardi' },
  { value: 3, label: 'Mercredi' },
  { value: 4, label: 'Jeudi' },
  { value: 5, label: 'Vendredi' },
  { value: 6, label: 'Samedi' },
]

export const MIN_DAY_OF_MONTH = 1
// Never 29-31: capped at 28 so "the Nth of every month" always exists,
// every month, without a leap-year or short-month special case — same
// reasoning a non-technical builder would expect without being told.
export const MAX_DAY_OF_MONTH = 28

export interface BuildCronParams {
  hour: number
  minute: number
  weekday?: number
  dayOfMonth?: number
}

// Builds a strict 5-field cron expression — minute hour day-of-month month
// day-of-week — and only ever this shape: never a 6-field (seconds) form,
// never an "@daily"/"@weekly"-style shorthand. Mirrors exactly what the
// backend's own assertFiveFieldCronExpression() (cron-schedule.ts) accepts.
export function buildCronExpression(frequency: ScheduleFrequency, params: BuildCronParams): string {
  const { hour, minute, weekday, dayOfMonth } = params
  if (frequency === 'daily') {
    return `${minute} ${hour} * * *`
  }
  if (frequency === 'weekly') {
    return `${minute} ${hour} * * ${weekday ?? 0}`
  }
  return `${minute} ${hour} ${dayOfMonth ?? MIN_DAY_OF_MONTH} * *`
}

export interface ParsedCronPreset {
  frequency: ScheduleFrequency
  hour: number
  minute: number
  weekday?: number
  dayOfMonth?: number
}

function toSimpleInt(field: string, min: number, max: number): number | null {
  // Deliberately only a single 1-2 digit integer — never a range ("1-5"),
  // list ("1,3"), or step ("*/2"). Any of those means this expression was
  // not generated by buildCronExpression() above, so it must fall back to
  // the advanced editor rather than being misrepresented as a preset.
  if (!/^\d{1,2}$/.test(field)) return null
  const value = Number(field)
  if (value < min || value > max) return null
  return value
}

// Recognizes ONLY the exact three shapes buildCronExpression() itself
// generates. Anything else — hand-written, produced by a future/older
// tool, or using cron syntax this UI doesn't model — returns null so the
// caller opens the advanced editor instead of silently reinterpreting (or
// worse, rewriting) an expression it doesn't actually understand.
export function parseCronPreset(cronExpression: string): ParsedCronPreset | null {
  const fields = cronExpression.trim().split(/\s+/)
  if (fields.length !== 5) return null
  const [minuteField, hourField, domField, monthField, dowField] = fields

  const minute = toSimpleInt(minuteField, 0, 59)
  const hour = toSimpleInt(hourField, 0, 23)
  if (minute === null || hour === null) return null

  if (domField === '*' && monthField === '*' && dowField === '*') {
    return { frequency: 'daily', hour, minute }
  }
  if (domField === '*' && monthField === '*' && dowField !== '*') {
    const weekday = toSimpleInt(dowField, 0, 6)
    if (weekday === null) return null
    return { frequency: 'weekly', hour, minute, weekday }
  }
  if (monthField === '*' && dowField === '*' && domField !== '*') {
    const dayOfMonth = toSimpleInt(domField, MIN_DAY_OF_MONTH, MAX_DAY_OF_MONTH)
    if (dayOfMonth === null) return null
    return { frequency: 'monthly', hour, minute, dayOfMonth }
  }
  return null
}

// Same 5-field-only rule the backend enforces on every scheduled trigger
// (never a 6-field/seconds form, never an "@..." shorthand) — checked here
// purely for a fast, friendly client-side error. The backend's own
// validateTrigger() remains the actual source of truth; this can never
// replace it.
export function isFiveFieldCron(cronExpression: string): boolean {
  const trimmed = cronExpression.trim()
  return trimmed.length > 0 && trimmed.split(/\s+/).length === 5
}

function pad2(value: number): string {
  return String(value).padStart(2, '0')
}

// French, frequency-only phrase — deliberately never folds the timezone
// into this string, so a caller always shows it as its own, clearly
// labelled piece of information rather than buried in prose.
export function describeCronHuman(cronExpression: string | null): string {
  if (!cronExpression) return 'Planification non définie'
  const parsed = parseCronPreset(cronExpression)
  if (!parsed) {
    return `Expression cron avancée : ${cronExpression}`
  }
  const time = `${pad2(parsed.hour)}:${pad2(parsed.minute)}`
  if (parsed.frequency === 'daily') {
    return `Tous les jours à ${time}`
  }
  if (parsed.frequency === 'weekly') {
    const label = WEEKDAY_OPTIONS.find((w) => w.value === parsed.weekday)?.label ?? '?'
    return `Chaque ${label.toLowerCase()} à ${time}`
  }
  return `Le ${parsed.dayOfMonth} de chaque mois à ${time}`
}

const FALLBACK_TIME_ZONES = [
  'UTC',
  'Europe/Paris',
  'Europe/London',
  'Indian/Antananarivo',
  'America/New_York',
  'America/Los_Angeles',
]

// Intl.supportedValuesOf('timeZone') is broadly supported (Node 18+,
// evergreen browsers) but is still a runtime API, not a syntax feature —
// wrapped defensively so an older/unusual environment degrades to a short
// static list instead of crashing the whole form.
//
// 'UTC' itself is deliberately force-included: it's the backend's own
// fallback default (AutomationsService.resolveTriggerTimezone()) and the
// obvious first choice for a non-technical user, but
// Intl.supportedValuesOf('timeZone') does not list it as a canonical zone
// name (only IANA area/location names like 'Etc/UTC' are) — without this,
// it would simply never appear in the dropdown.
export function listIanaTimeZones(): string[] {
  try {
    const zones = Intl.supportedValuesOf('timeZone')
    if (zones.length === 0) return FALLBACK_TIME_ZONES
    return zones.includes('UTC') ? zones : ['UTC', ...zones]
  } catch {
    return FALLBACK_TIME_ZONES
  }
}

export function detectBrowserTimeZone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
  } catch {
    return 'UTC'
  }
}

// Codex review fix: listIanaTimeZones() is a snapshot of this runtime's own
// canonical IANA zone database — it is not guaranteed to contain the
// browser's own detected zone, a zone saved earlier from a different
// browser/OS, or an alias the backend itself accepts but this particular
// runtime doesn't list canonically. A <select> built only from
// listIanaTimeZones() could therefore silently drop the current value on
// load, changing it to a different zone the instant the form is saved
// without the user ever touching the field. This guarantees `current` is
// present — inserted first if missing, never duplicated if already
// there — and must be called with the *live* current value (create: the
// detected browser zone; edit: trigger.timezone), never baked into a
// static, one-time list.
export function ensureTimeZoneOption(zones: string[], current: string | null | undefined): string[] {
  if (!current) return zones
  return zones.includes(current) ? zones : [current, ...zones]
}

// Renders an ISO instant (as stored/returned by the backend, always UTC)
// in a given IANA zone, in French — the zone itself is always appended
// rather than left implicit, per the "never hide the reference timezone"
// requirement: a bare "18/09/2026 09:00" would silently be read in the
// viewer's own local time, which is not necessarily the automation's own
// timezone.
//
// Codex review fix: `timeZone` can be a value this particular runtime
// doesn't recognize (accepted by the backend, or by a different/newer
// browser, but unknown to an older one) — Intl.DateTimeFormat throws a
// RangeError in that case. Never let that crash the list/detail page:
// degrade to UTC, but say so explicitly and keep naming the zone that was
// actually requested, so the UTC instant is never mistaken for the
// automation's own timezone. An invalid ISO instant is handled the same
// defensive way, never thrown.
export function formatInstantInTimeZone(iso: string, timeZone: string): string {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) {
    return 'Date invalide'
  }
  try {
    const formatted = new Intl.DateTimeFormat('fr-FR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZone,
    }).format(date)
    return `${formatted} (${timeZone})`
  } catch {
    const utcFormatted = new Intl.DateTimeFormat('fr-FR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZone: 'UTC',
    }).format(date)
    return `${utcFormatted} UTC (repli : fuseau « ${timeZone} » non reconnu par ce navigateur)`
  }
}

export function formatNextRunAt(nextRunAt: string | null, timezone: string | null): string {
  if (!nextRunAt) return 'Non planifiée'
  return formatInstantInTimeZone(nextRunAt, timezone ?? 'UTC')
}

// Shown next to any nextRunAt display — the scheduler ticks once a minute
// (see AutomationSchedulerService), so an occurrence can land up to
// ~60s after the instant shown here.
export const SCHEDULER_RESOLUTION_NOTE =
  'Le planificateur vérifie les automatisations dues environ une fois par minute : une exécution peut donc démarrer jusqu’à une minute après l’heure indiquée.'
