import type { ComponentProps } from 'react';
import type Ionicons from '@expo/vector-icons/Ionicons';

// Outline by default; filled for selected navigation. Same meaning on every platform.
export const APP_ICONS = {
  home: ['home-outline', 'home'],
  visibility: ['eye-outline', 'eye'],
  activity: ['layers-outline', 'layers'],
  profile: ['person-circle-outline', 'person-circle'],
  audit: ['scan-outline', 'scan'],
  opportunity: ['bulb-outline', 'bulb'],
  document: ['document-text-outline', 'document-text'],
  library: ['library-outline', 'library'],
  tasks: ['checkbox-outline', 'checkbox'],
  applications: ['briefcase-outline', 'briefcase'],
  analytics: ['stats-chart-outline', 'stats-chart'],
  assistant: ['sparkles-outline', 'sparkles'],
  automation: ['git-branch-outline', 'git-branch'],
  validation: ['shield-checkmark-outline', 'shield-checkmark'],
  website: ['globe-outline', 'globe'],
  integrations: ['extension-puzzle-outline', 'extension-puzzle'],
  organization: ['business-outline', 'business'],
  location: ['location-outline', 'location'],
  store: ['storefront-outline', 'storefront'],
  social: ['people-outline', 'people'],
  competitors: ['git-compare-outline', 'git-compare'],
  insights: ['analytics-outline', 'analytics'],
  support: ['headset-outline', 'headset'],
  help: ['help-circle-outline', 'help-circle'],
  email: ['mail-outline', 'mail'],
  deliveries: ['paper-plane-outline', 'paper-plane'],
  billing: ['card-outline', 'card'],
  password: ['lock-closed-outline', 'lock-closed'],
  settings: ['settings-outline', 'settings'],
  logout: ['log-out-outline', 'log-out'],
  login: ['log-in-outline', 'log-in'],
  register: ['person-add-outline', 'person-add'],
  user: ['person-outline', 'person'],
  search: ['search-outline', 'search'],
  emptySearch: ['search-outline', 'search'],
  showPassword: ['eye-outline', 'eye'],
  hidePassword: ['eye-off-outline', 'eye-off'],
  back: ['arrow-back', 'arrow-back'],
  forward: ['arrow-forward', 'arrow-forward'],
  chevron: ['chevron-forward', 'chevron-forward'],
  close: ['close', 'close'],
  add: ['add', 'add'],
  check: ['checkmark', 'checkmark'],
  error: ['alert-circle-outline', 'alert-circle'],
  warning: ['warning-outline', 'warning'],
  info: ['information-circle-outline', 'information-circle'],
  history: ['time-outline', 'time'],
  clock: ['time-outline', 'time'],
  calendar: ['calendar-outline', 'calendar'],
  edit: ['create-outline', 'create'],
  code: ['code-slash-outline', 'code-slash'],
  performance: ['speedometer-outline', 'speedometer'],
  faq: ['chatbubbles-outline', 'chatbubbles'],
  reviewReply: ['chatbox-ellipses-outline', 'chatbox-ellipses'],
  publication: ['megaphone-outline', 'megaphone'],
  folder: ['folder-open-outline', 'folder-open'],
  list: ['list-outline', 'list'],
  grid: ['grid-outline', 'grid'],
  board: ['albums-outline', 'albums'],
  sort: ['swap-vertical-outline', 'swap-vertical'],
  organize: ['options-outline', 'options'],
  addTask: ['add-circle-outline', 'add-circle'],
  upload: ['cloud-upload-outline', 'cloud-upload'],
  save: ['save-outline', 'save'],
  approve: ['checkmark-circle-outline', 'checkmark-circle'],
  reject: ['close-circle-outline', 'close-circle'],
  share: ['share-outline', 'share'],
  download: ['download-outline', 'download'],
  refresh: ['refresh-outline', 'refresh'],
  delete: ['trash-outline', 'trash'],
  attachment: ['attach-outline', 'attach'],
  send: ['send-outline', 'send'],
  archive: ['archive-outline', 'archive'],
} as const satisfies Record<string, readonly [ComponentProps<typeof Ionicons>['name'], ComponentProps<typeof Ionicons>['name']]>;

export type AppIconName = keyof typeof APP_ICONS;

// Navigation cards derive their symbol from the destination, never from translated text.
export const ROUTE_ICONS: Readonly<Record<string, AppIconName>> = {
  '/settings': 'settings', '/integrations': 'integrations', '/websites': 'website',
  '/social': 'social', '/business-profile': 'store', '/locations': 'location',
  '/location-import': 'upload', '/audit': 'audit', '/history': 'history',
  '/intelligence': 'insights', '/competitors': 'competitors', '/reports': 'analytics',
  '/automations': 'automation', '/notifications': 'deliveries', '/programs': 'applications',
  '/validations': 'validation', '/billing': 'billing', '/support': 'support',
};
