import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Building2, Check, ChevronRight, CircleAlert, Link2, MapPin, Plus, Radar, RefreshCw, Store, Trash2, Unplug } from "lucide-react";
import { getCurrentOrganization, type Organization } from "../lib/api";
import { readBusinessLocations, readGoogleBusinessConnection, saveBusinessLocations, saveGoogleBusinessConnection, type BusinessLocation, type GoogleBusinessConnection } from "../lib/business-profile";

const EMPTY_LOCATION = { name: "", address: "", city: "", country: "Madagascar", phone: "" };
type LocationForm = typeof EMPTY_LOCATION;

function Step({ number, title, active, done }: { number: number; title: string; active: boolean; done: boolean }) {
  return <div className="flex items-center gap-2"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${done ? "bg-teal text-white" : active ? "bg-navy text-white" : "bg-border-light text-muted"}`}>{done ? <Check size={14} /> : number}</span><span className={`text-xs font-semibold ${active ? "text-navy" : "text-muted"}`}>{title}</span></div>;
}

export default function BusinessProfilePage() {
  const [organization, setOrganization] = useState<Organization | null>(null);
  const [locations, setLocations] = useState<BusinessLocation[]>(readBusinessLocations);
  const [connection, setConnection] = useState<GoogleBusinessConnection>(readGoogleBusinessConnection);
  const [form, setForm] = useState<LocationForm>(EMPTY_LOCATION);
  const [showForm, setShowForm] = useState(() => locations.length === 0);
  const [tab, setTab] = useState<"locations" | "google">("locations");
  const [notice, setNotice] = useState("");

  useEffect(() => { getCurrentOrganization().then(setOrganization).catch(() => undefined); }, []);
  useEffect(() => { saveBusinessLocations(locations); }, [locations]);
  useEffect(() => { saveGoogleBusinessConnection(connection); }, [connection]);

  const completeLocations = locations.length > 0;
  const googleConnected = connection.status === "connected";
  const profileProgress = useMemo(() => (completeLocations ? 50 : 0) + (googleConnected ? 50 : 0), [completeLocations, googleConnected]);
  function update(field: keyof LocationForm, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  function addLocation(event: FormEvent) { event.preventDefault(); if (!form.name.trim() || !form.address.trim() || !form.city.trim()) return; const location: BusinessLocation = { id: crypto.randomUUID(), name: form.name.trim(), address: form.address.trim(), city: form.city.trim(), country: form.country.trim() || "Madagascar", phone: form.phone.trim(), primary: locations.length === 0 }; setLocations((current) => [...current, location]); setForm(EMPTY_LOCATION); setShowForm(false); setNotice("Établissement ajouté au profil entreprise."); }
  function removeLocation(id: string) { setLocations((current) => { const next = current.filter((location) => location.id !== id); if (next.length && !next.some((location) => location.primary)) next[0] = { ...next[0], primary: true }; return next; }); }
  function prepareGoogleConnection() { setConnection({ status: "pending" }); setNotice("Parcours OAuth préparé. Le backend Google doit maintenant fournir l’URL d’autorisation."); }
  function disconnectGoogle() { setConnection({ status: "disconnected" }); setNotice("Connecteur Google déconnecté de cet espace."); }

  return <div className="mx-auto max-w-7xl animate-slide-up p-5 md:p-6 lg:p-8">
    <header className="mb-7 border-b border-border pb-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-teal-dark"><Radar size={15} /> Présence locale ROBIA</p><h1 className="text-[30px] font-bold leading-tight tracking-[-0.035em] text-navy md:text-[36px]">Relier l’entreprise à ses lieux réels</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">Configurez les établissements de {organization?.name ?? "votre entreprise"}, puis associez-les à Google Business Profile.</p></div><div className="min-w-64 border-l-2 border-teal pl-4"><div className="flex justify-between text-[10px] font-bold uppercase tracking-wide text-muted"><span>Configuration</span><span>{profileProgress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-border-light"><div className="h-full bg-teal transition-all" style={{ width: `${profileProgress}%` }} /></div></div></div></header>

    <div className="mb-6 flex flex-wrap items-center gap-3 border-y border-border py-4"><Step number={1} title="Entreprise" active={false} done={Boolean(organization)} /><ChevronRight size={14} className="text-border" /><Step number={2} title="Établissements" active={tab === "locations"} done={completeLocations} /><ChevronRight size={14} className="text-border" /><Step number={3} title="Google Business Profile" active={tab === "google"} done={googleConnected} /></div>
    {notice && <div role="status" className="mb-5 flex items-start gap-2 border-l-2 border-electric bg-electric-light px-4 py-3 text-sm text-electric-dark"><CircleAlert size={17} className="mt-0.5 shrink-0" /><span>{notice}</span><button className="ml-auto text-xs font-bold" onClick={() => setNotice("")}>Fermer</button></div>}
    <div className="mb-7 flex border-b border-border"><button onClick={() => setTab("locations")} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === "locations" ? "border-teal text-navy" : "border-transparent text-muted"}`}>Établissements</button><button onClick={() => setTab("google")} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === "google" ? "border-teal text-navy" : "border-transparent text-muted"}`}>Connecteur Google</button></div>

    {tab === "locations" ? <div className="grid gap-8 lg:grid-cols-[1fr_340px]">
      <section className="border-t-2 border-teal bg-white"><div className="flex items-center justify-between border-b border-border px-1 py-4"><div><h2 className="font-bold text-navy">Établissements visibles</h2><p className="mt-1 text-xs text-muted">Un profil par adresse accueillant des clients.</p></div><button onClick={() => setShowForm(true)} className="inline-flex items-center gap-2 rounded-lg bg-orange px-3.5 py-2 text-xs font-bold text-white hover:bg-orange-dark"><Plus size={15} />Ajouter</button></div><div className="divide-y divide-border">{locations.length === 0 ? <div className="p-10 text-center"><Store size={28} className="mx-auto mb-3 text-muted" /><p className="font-semibold text-navy">Aucun établissement</p><p className="mt-1 text-sm text-muted">Ajoutez l’adresse principale de votre entreprise.</p></div> : locations.map((location) => <article key={location.id} className="flex items-start gap-4 py-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-teal-light text-teal-dark"><MapPin size={18} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-navy">{location.name}</h3>{location.primary && <span className="text-[10px] font-bold uppercase tracking-wide text-teal-dark">Principal</span>}</div><p className="mt-1 text-sm text-muted">{location.address}, {location.city}, {location.country}</p>{location.phone && <p className="mt-1 text-xs text-muted">{location.phone}</p>}</div><button onClick={() => removeLocation(location.id)} aria-label={`Supprimer ${location.name}`} className="rounded-lg p-2 text-muted hover:bg-red-50 hover:text-red-600"><Trash2 size={16} /></button></article>)}</div></section>
      <aside className="border-t border-border pt-5"><h2 className="font-bold text-navy">{showForm ? "Nouvel établissement" : "Profil entreprise"}</h2>{showForm ? <form onSubmit={addLocation} className="mt-4 space-y-3">{([['name','Nom public','Boutique Centre-ville'],['address','Adresse','12 avenue de l’Indépendance'],['city','Ville','Antananarivo'],['country','Pays','Madagascar'],['phone','Téléphone','+261 34 00 000 00']] as const).map(([field,label,placeholder]) => <label key={field} className="block"><span className="mb-1.5 block text-xs font-bold text-navy">{label}{field !== 'country' && field !== 'phone' ? ' *' : ''}</span><input required={field !== 'country' && field !== 'phone'} value={form[field]} onChange={(event) => update(field,event.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-border px-3.5 py-2.5 text-sm outline-none focus:border-teal focus:ring-2 focus:ring-teal/15" /></label>)}<div className="flex gap-2 pt-2"><button type="submit" className="flex-1 rounded-lg bg-navy py-2.5 text-sm font-bold text-white">Enregistrer</button>{locations.length > 0 && <button type="button" onClick={() => setShowForm(false)} className="rounded-lg border border-border px-3 text-sm text-muted">Annuler</button>}</div></form> : <div className="mt-4 border-l-2 border-orange bg-orange-light/25 p-4"><Building2 size={20} className="text-orange-dark" /><h3 className="mt-3 font-bold text-navy">{organization?.name ?? "Entreprise"}</h3><p className="mt-1 text-sm text-muted">{locations.length} établissement{locations.length > 1 ? "s" : ""} configuré{locations.length > 1 ? "s" : ""}.</p><button onClick={() => setTab("google")} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-teal-dark">Continuer vers Google <ChevronRight size={16} /></button></div>}</aside>
    </div> : <section className="grid border-t-2 border-teal bg-white lg:grid-cols-[1fr_340px]"><div className="p-1 py-6 lg:pr-8"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-navy text-lg font-bold text-white">G</div><h2 className="mt-5 text-xl font-bold text-navy">Google Business Profile</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted">Importez les établissements administrés par le compte Google et associez-les aux lieux ROBIA.</p><div className="mt-6 space-y-3">{["Importer les établissements Google", "Associer chaque lieu à ROBIA", "Contrôler les informations synchronisées"].map((item) => <div key={item} className="flex items-center gap-3 text-sm text-dark"><Check size={15} className="text-teal-dark" />{item}</div>)}</div>{connection.status === "connected" ? <button onClick={disconnectGoogle} className="mt-7 inline-flex items-center gap-2 rounded-lg border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600"><Unplug size={16} />Déconnecter Google</button> : <button onClick={prepareGoogleConnection} disabled={!completeLocations} className="mt-7 inline-flex items-center gap-2 rounded-lg bg-navy px-4 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Link2 size={16} />{connection.status === "pending" ? "Reprendre la connexion" : "Connecter Google Business Profile"}</button>}{!completeLocations && <p className="mt-2 text-xs text-orange-dark">Ajoutez au moins un établissement avant de connecter Google.</p>}</div><aside className="border-t border-border bg-slate-bg p-6 lg:border-t-0 lg:border-l"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted">État du connecteur</p><div className="mt-4 flex items-center gap-3 border-l-2 border-teal bg-white px-4 py-3"><span className={`h-3 w-3 rounded-full ${googleConnected ? "bg-teal" : connection.status === "pending" ? "bg-orange" : "bg-slate-300"}`} /><div><p className="font-bold text-navy">{googleConnected ? "Connecté" : connection.status === "pending" ? "En attente d’OAuth" : "Non connecté"}</p><p className="text-xs text-muted">{googleConnected ? connection.accountEmail : "Aucun compte Google autorisé"}</p></div></div><div className="mt-4 border-l-2 border-orange bg-orange-light/40 px-4 py-3 text-xs leading-5 text-orange-dark"><strong>Backend requis.</strong> La connexion réelle nécessite OAuth et un callback serveur.</div>{connection.status === "pending" && <button onClick={() => setConnection({ status: "disconnected" })} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-muted"><RefreshCw size={14} />Réinitialiser</button>}</aside></section>}
  </div>;
}